### ISSUE TITLE
Reproducing the forecasts

### ISSUE THREAD

**Issue by kf-rahman** [tom-andersson/icenet-paper#12]
Hello,
If I were to reproduce the forecasts shown in the research-paper. What are my options? Are the weights available anywhere for me to use or do I have to train the model locally.

**Comment by tom-andersson** [comment]
Hey @kf-rahman,

Unfortunately we don't have the functionality for this in this codebase, but it shouldn't be too hard to do: download each of the trained network h5 files from the PDC dataset linked in the readme, and save them with the file paths expected by the codebase (you can use [this bash script](https://github.com/tom-andersson/icenet-paper/blob/main/download_paper_generated_data.sh) for reference).

These notebooks may also be useful:
- https://edsbook.org/notebooks/gallery/ac327c3a-5264-40a2-8c6e-1e8d7c4b37ef/notebook
- https://github.com/nci/icenet/blob/main/notebook/icenet-prediction.ipynb
