### ISSUE TITLE
Issues with downloading cmip6 MRI-ESM2-0 data

### ISSUE THREAD

**Issue by xinaesthete** [tom-andersson/icenet-paper#4]
I don't think this is the result of mis-configuration etc at my end - from my understanding this part of the code doesn't depend on any API keys, or any complex python dependencies being properly set up etc.

FWIW I've been trying to run this on Windows, with shell scripts slightly modified to .cmd equivalents... which feels like a bit of a sub-optimal approach, and I'm fairly sure not directly relevant here, although earlier I had another problem that was to do with a weirdly escaped character making its way into some config somewhere. I suppose it's marginally plausible that something related could have somehow snuck in (fairly infinitesimal chance I'd say).

It appears that with `--source_id = MRI-ESM-2-0`, `download_cmip6_data.py` is getting empty results from `esgf_search()`. EC bits completed ok AFAICT... I dug in a little bit more, and find that, for example, a request to 

`https://esgf-node.llnl.gov/esg-search/search/?source_id=MRI-ESM2-0&member_id=r1i1p1f1&frequency=mon&variable_id=siconca&table_id=SImon&grid_label=gn&experiment_id=ssp245&data_node=esgf-data2.diasjp.net&project=CMIP6&type=File&latest=true&format=application%2Fsolr%2Bjson&offset=0`

returns

```json
{
    "responseHeader": {
        "status": 0,
        "QTime": 1343,
        "params": {
            "df": "text",
            "q.alt": "*:*",
            "indent": "true",
            "echoParams": "all",
            "fl": "*,score",
            "start": "0",
            "fq": [
                "type:File",
                "source_id:\"MRI-ESM2-0\"",
                "member_id:\"r1i1p1f1\"",
                "frequency:\"mon\"",
                "variable_id:\"siconca\"",
                "table_id:\"SImon\"",
                "grid_label:\"gn\"",
                "experiment_id:\"ssp245\"",
                "data_node:\"esgf-data2.diasjp.net\"",
                "project:\"CMIP6\"",
                "latest:true"
            ],
            "sort": "id asc",
            "rows": "10",
            "q": "*:*",
            "shards": "localhost:8983/solr/files,localhost:8985/solr/files,localhost:8988/solr/files,localhost:8990/solr/files,localhost:8993/solr/files,localhost:8995/solr/files,localhost:8987/solr/files",
            "tie": "0.01",
            "facet.limit": "2048",
            "qf": "text",
            "facet.method": "fc",
            "facet.mincount": "1",
            "wt": "json",
            "facet.sort": "lex"
        }
    },
    "response": {
        "numFound": 0,
        "start": 0,
        "maxScore": 0.0,
        "docs": []
    }
}
```

p.s. excuse the silly internet pseudonym; this is Peter, we met at AI UK...

**Comment by tom-andersson** [comment]
Thanks for raising this @xinaesthete. It could be that the data centre providing the MRI-ESM2 data has changed (or something similar) meaning the config options are wrong now. I'll try rerunning this myself soon, although I'm away from my work laptop for a few weeks I'm afraid. Keep me posted if you find a solution!

**Comment by xinaesthete** [comment]
Thanks @tom-andersson 

I started looking for alternate sources... CEDA archive seems promising, I've been trying to see if I can harvest that via their CSW, as URIs like `https://data.ceda.ac.uk/badc/cmip6/data/CMIP6/ScenarioMIP/MRI/MRI-ESM2-0/ssp245/r1i1p1f1/SImon/siconca/gn/v20190904/siconca_SImon_MRI-ESM2-0_ssp245_r1i1p1f1_gn_201501-210012.nc` seem to have parts that I may not be able to reliably build programmatically... So I installed `OWSLib`, started trying to poke around with that.

I am currently getting errors that seem to boil down to

`SSLError(CertificateError("hostname 'csw1.ceda.ac.uk' doesn't match 'csw.ceda.ac.uk'")))`

That doesn't seem to be user-error on my part, although I'm out of my usual comfort zone with some of this stuff, so always chances for naivety of some kind to be a factor.

Anyway, my curiosity is somewhat piqued and at least I'm learning a bit through the process (not that mismatched hostnames are particularly interesting in and of themselves).

**Comment by xinaesthete** [comment]
Leaving out `'data_node'` in the query seems to be working.

**Comment by bryandunn614** [comment]
Same issue here,now directly run  ./download_cmip6_data_in_parallel.sh will get error message from log/cmip6_download_logs/,all MRI  txt files report error message,one of them(MRI_r1i1p1f1.txt,for instance) is just like this:

Downloading data for MRI-ESM2-0, r1i1p1f1



siconca: searching ESGF... found 0 files. loading metadata... Traceback (most recent call last):
  File "icenet/download_cmip6_data.py", line 334, in <module>
    cmip6_da = xr.open_mfdataset(results, combine='by_coords', chunks={'time': '499MB'})[variable_id]
  File "/home/bryan/anaconda3/envs/icenet/lib/python3.7/site-packages/xarray/backends/api.py", line 921, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open

**Comment by bryandunn614** [comment]
> Leaving out `'data_node'` in the query seems to be working.

Hello @xinaesthete ,what do you mean leave out,I tried to comment line 310 of download_cmip6_data.py,just as:
_# query['data_node'] = data_node_


log file will not report an error,however when run ./rotate_wind_data_in_parallel.sh will report error message,
**_OSError: One or more of the files specified did not exist.
    * "/mnt/e/icenet-paper/data/cmip6/EC-Earth3/r14i1p1f1/uas_EASE_cmpr.nc" didn't match any files_**
data/cmip6/EC-Earth3 and data/cmip6/MRI-ESM2-0 each of subfiles  only has the file siconca_latlon.nc, not uas_EASE_cmpr.nc

I  have stuck here for a long time,I think it is because download_cmip6_data.py can not download data from the website correctly now

**Comment by JimCircadian** [comment]
Hello all. I don't look after this repository but worked on the newer [IceNet codebase](https://github.com/icenet-ai/icenet). If you're struggling to download data using this original code, you can perhaps look at the implementation for `icenet_data_cmip`, though for daily forecasting in the new version we don't use it often, it was working a few months back. 

A lot of the time, there can be issues with the remote servers, so the newer command I refer to above has additional features that allow you exclude troublesome [ESGF nodes](https://github.com/icenet-ai/icenet/issues/26), for example. 

To make this work with the icenet-paper codebase, you'll need to consider that `icenet_data_cmip`'s implementation is for a daily timescale, but obviously `download_cmip6_data.py` in here has the original monthly download code, so you can perhaps update that script and submit it as an update to this repository. There is an [issue](https://github.com/icenet-ai/icenet/issues/22) and [initiative](https://github.com/icenet-ai/icenet-project/issues/49) around replicating the original paper pipeline. 

We don't actively develop against this repository so some updates that account for the changing state of the ESGF network might not be backported, but we would I think welcome any changes that you wish to make to solve that!

Thanks and I hope this helps 😉

**Comment by Bryan614** [comment]
Hello  Mr.@tom-andersson and @JimCircadian 
I have found the issue of downloading cmip6 EC-Earth3 data,because running the single python command takes a 12GB memory.So when I run the parallel.sh memory will be used up and overflowed so Ubuntu will just kill the command without any report in log,which make me think it has finished successfully.I run the program on my laptop with memory of 16GB.
For MRI-ESM2 download,first the download link in python file can not connect right now(a data node in Japan).I try to use other data node to see if it can download successfully,the other issue maybe the MRI-ESM2 dataset may change its format.
I am wondering if I can’t download MRI-ESM2 successfully,can I just use EC-Earth3 for pre-training process,thank you.

**Comment by xinaesthete** [comment]
For what it's worth, with a lot of nursing over the course of about a week, I think I did manage to download all of the data eventually - I'd like to get back to it at some point.

As I recall, without `data_node` it was picking randomly, and the download speeds were generally excruciatingly slow - I guess how well a given node works might also depend a bit on which region you're in. So hopefully it will work with the updated script, but if it's very slow it might still be worth trying with different values.

**Comment by bryandunn614** [comment]
Thank you @tom-andersson  for solving these problems,it has  been bothering me for couple of weeks
