### ISSUE TITLE
./download_seas5_forecasts_in_parallel.sh laton folder is empty

### ISSUE THREAD

**Issue by bryandunn614** [tom-andersson/icenet-paper#8]
Hello,
     After checking the logs and data folder,one of the logs is:   
```
Regridding to EASE... ut_scale(): NULL factor argument
ut_are_convertible(): NULL unit argument
/scratch/zv32/cd8380/mambaforge/envs/icenet/lib/python3.7/site-packages/iris/fileformats/_pyke_rules/compiled_krb/fc_rules_cf_fc.py:2190: UserWarning: Ignoring netCDF variable 'siconc' invalid units '(0 - 1)'
  warnings.warn(msg)
Deleting existing file.
Done
Done.
```
 And the laton folder is empty,I run the programme on the cloud server which reported finished successfully,but it seems that there is something wrong

**Comment by tom-andersson** [comment]
The raw SEAS5 forecasts are deleted from the `data/forecasts/seas5/latlon/` folder after they're regridded to EASE into the `EASE/` folder. See:
https://github.com/tom-andersson/icenet-paper/blob/4eed8998a944744f0397e587019dbdefac16e31c/icenet/download_seas5_forecasts.py#L50
